-- Spot: public read/create, owner-only update/delete.
-- No client receives a table grant or an owner identifier.
begin;

create table if not exists public.spots (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(btrim(name)) between 1 and 200),
  area text not null check (char_length(btrim(area)) between 1 and 200),
  category text not null check (char_length(btrim(category)) between 1 and 100),
  note text not null check (char_length(btrim(note)) between 1 and 2000),
  lat numeric not null check (lat between -90 and 90),
  lng numeric not null check (lng between -180 and 180),
  owner_id uuid references auth.users(id) on delete set null,
  legacy_owner_id bigint,
  created_at timestamptz not null default now()
);
create index if not exists spots_owner_created_idx on public.spots(owner_id, created_at desc);
create index if not exists spots_created_idx on public.spots(created_at desc, id);
alter table public.spots enable row level security;
revoke all on public.spots from public, anon, authenticated;
revoke all on sequence public.spots_id_seq from public, anon, authenticated;

-- A narrow RPC boundary is intentional: no UUID owner IDs in public data,
-- and ownership can only be assigned from the signed JWT, never a payload.
create or replace function public.list_spots(p_limit integer default 1000, p_offset integer default 0)
returns table(id bigint, name text, area text, category text, note text, lat numeric, lng numeric, created_at timestamptz)
language sql stable security definer set search_path = ''
as $$
  select s.id, s.name, s.area, s.category, s.note, s.lat, s.lng, s.created_at
  from public.spots s
  order by s.created_at desc, s.id
  limit least(greatest(coalesce(p_limit, 1000), 1), 1000)
  offset greatest(coalesce(p_offset, 0), 0);
$$;

create or replace function public.count_spots()
returns bigint language sql stable security definer set search_path = ''
as $$ select count(*) from public.spots; $$;

create or replace function public.my_spots()
returns table(id bigint, name text, area text, category text, note text, lat numeric, lng numeric, created_at timestamptz)
language plpgsql stable security definer set search_path = ''
as $$
begin
  if auth.uid() is null then
    raise exception 'authentication_required' using errcode = '42501';
  end if;
  return query
    select s.id, s.name, s.area, s.category, s.note, s.lat, s.lng, s.created_at
    from public.spots s where s.owner_id = auth.uid()
    order by s.created_at desc, s.id;
end;
$$;

create or replace function public.create_spot(
  p_name text, p_area text, p_category text, p_note text, p_lat numeric, p_lng numeric
)
returns bigint language plpgsql security definer set search_path = ''
as $$
declare new_id bigint;
begin
  insert into public.spots(name, area, category, note, lat, lng, owner_id)
  values (btrim(p_name), btrim(p_area), btrim(p_category), btrim(p_note), p_lat, p_lng, auth.uid())
  returning id into new_id;
  return new_id;
end;
$$;

create or replace function public.update_spot(
  p_id bigint, p_name text, p_area text, p_category text, p_note text
)
returns boolean language plpgsql security definer set search_path = ''
as $$
declare affected integer;
begin
  if auth.uid() is null then
    raise exception 'authentication_required' using errcode = '42501';
  end if;
  update public.spots set name = btrim(p_name), area = btrim(p_area),
    category = btrim(p_category), note = btrim(p_note)
  where id = p_id and owner_id = auth.uid();
  get diagnostics affected = row_count;
  if affected = 0 then
    raise exception 'not_found_or_not_owned' using errcode = '42501';
  end if;
  return true;
end;
$$;

create or replace function public.delete_spot(p_id bigint)
returns boolean language plpgsql security definer set search_path = ''
as $$
declare affected integer;
begin
  if auth.uid() is null then
    raise exception 'authentication_required' using errcode = '42501';
  end if;
  delete from public.spots where id = p_id and owner_id = auth.uid();
  get diagnostics affected = row_count;
  if affected = 0 then
    raise exception 'not_found_or_not_owned' using errcode = '42501';
  end if;
  return true;
end;
$$;

revoke all on function public.list_spots(integer, integer) from public, anon, authenticated;
revoke all on function public.count_spots() from public, anon, authenticated;
revoke all on function public.my_spots() from public, anon, authenticated;
revoke all on function public.create_spot(text, text, text, text, numeric, numeric) from public, anon, authenticated;
revoke all on function public.update_spot(bigint, text, text, text, text) from public, anon, authenticated;
revoke all on function public.delete_spot(bigint) from public, anon, authenticated;
grant usage on schema public to anon, authenticated;
grant execute on function public.list_spots(integer, integer) to anon, authenticated;
grant execute on function public.count_spots() to anon, authenticated;
grant execute on function public.create_spot(text, text, text, text, numeric, numeric) to anon, authenticated;
grant execute on function public.my_spots() to authenticated;
grant execute on function public.update_spot(bigint, text, text, text, text) to authenticated;
grant execute on function public.delete_spot(bigint) to authenticated;

comment on table public.spots is 'Spot app data; direct anonymous/authenticated table access is denied. Use narrow RPC functions.';
comment on function public.create_spot(text, text, text, text, numeric, numeric) is 'Guest creation allowed. Owner is always auth.uid(), never provided by the client.';

commit;
